version: '3.9'

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: giftsforprogrammers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5432:5432"

secrets:
  db_password:
    file: db_password.secret.txt
